export const supabaseUrl = 'https://uqejfbljzcwonhspvtgr.supabase.co';
export const supabaseAnonKey =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxZWpmYmxqemN3b25oc3B2dGdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxNDMwOTUsImV4cCI6MjA3OTcxOTA5NX0.y9hyi8qOdBUwlIqTQf9_HxCg7UqkyUv7rMWxeb6UTfo';

//  https://uqejfbljzcwonhspvtgr.supabase.co/rest/v1/audio_chunks?select=*&call_id=eq.CALL_ID&order=timestamp.asc", { headers: { apikey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxZWpmYmxqemN3b25oc3B2dGdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxNDMwOTUsImV4cCI6MjA3OTcxOTA5NX0.y9hyi8qOdBUwlIqTQf9_HxCg7UqkyUv7rMWxeb6UTfo", Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxZWpmYmxqemN3b25oc3B2dGdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxNDMwOTUsImV4cCI6MjA3OTcxOTA5NX0.y9hyi8qOdBUwlIqTQf9_HxCg7UqkyUv7rMWxeb6UTfo" }} "
